
name: APIPractice Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Execute Tests
      run: mvn clean test -Dsuite=userProfileService -X

    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Logs
        path: output/logs/

    - name: Publish Test Report
      if: always()
      uses: turing85/publish-report@v2.1.1
      with:
        name: Result
        path: target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit
      

